apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-service.fullname" . }}
  labels:
    {{- include "app-service.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ printf "http-%s-port" (include "app-service.fullname" .) | trunc 15 | trimSuffix "-" }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containers.ports.containerPort }}
      protocol: TCP
  selector:
    {{- include "app-service.selectorLabels" . | nindent 4 }}
